In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
PATH = "../data/raw/listings.csv"
df_airbnb = pd.read_csv(PATH)

# Display all the columns
pd.set_option('display.max_columns', None)

In [3]:
df_airbnb.shape

(6334, 79)

In [4]:
df_airbnb.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,132068,https://www.airbnb.com/rooms/132068,20250929230956,2025-09-30,city scrape,Great attic+terrace+parking. Beach views. ESS0...,"Amazing modern, clean & fully equiped flat of...",Gros is the trendy neighborhood of Donosti. Th...,https://a0.muscache.com/pictures/hosting/Hosti...,648938,https://www.airbnb.com/users/show/648938,Mikel,2011-05-31,"San Sebastian, Spain",Nací y crecí en San Sebastian. Al igual que vo...,within an hour,100%,100%,t,https://a0.muscache.com/im/users/648938/profil...,https://a0.muscache.com/im/users/648938/profil...,NaN,1.0,1.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Basque Country, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.324750,-1.973350,Entire condo,Entire home/apt,4,1.0,1 bath,2.0,3.0,"[""Refrigerator"", ""Microwave"", ""Essentials"", ""W...",$201.00,1,63,1.0,2.0,63.0,63.0,1.8,63.0,NaN,t,2,16,34,273,2025-09-30,818,69,6,37,67,255,51255.0,2011-06-04,2025-09-28,4.89,4.90,4.78,4.97,4.97,4.94,4.76,ESFCTU00002000700022477500000000000000000000ES...,t,1,1,0,0,4.69
1,225692,https://www.airbnb.com/rooms/225692,20250929230956,2025-09-30,city scrape,"Parte Vieja, San Sebastian",NaN,NaN,https://a0.muscache.com/pictures/31866298/de9d...,1176053,https://www.airbnb.com/users/show/1176053,Julia,2011-09-18,"San Sebastian, Spain","Hola, soy Julia, el de la foto es mi pequeño t...",within a few hours,100%,94%,t,https://a0.muscache.com/im/users/1176053/profi...,https://a0.muscache.com/im/users/1176053/profi...,NaN,1.0,1.0,"['email', 'phone']",t,t,NaN,Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.324942,-1.982063,Entire rental unit,Entire home/apt,6,1.0,1 bath,3.0,4.0,"[""Pack \u2019n play/Travel crib"", ""Refrigerato...",$173.00,2,365,2.0,3.0,365.0,365.0,2.3,365.0,NaN,t,13,18,18,147,2025-09-30,293,25,0,18,30,150,25950.0,2011-10-12,2025-08-22,4.83,4.87,4.90,4.89,4.93,4.95,4.77,ESS00994,f,1,1,0,0,1.72
2,309812,https://www.airbnb.com/rooms/309812,20250929230956,2025-09-30,city scrape,Impresionante vivienda céntrica con vistas al mar,NaN,The apartment is located in the Romantic Area ...,https://a0.muscache.com/pictures/50826406/0c15...,1589633,https://www.airbnb.com/users/show/1589633,Emy,2012-01-10,"San Sebastian, Spain",My name is Emy and I am the owner of these apa...,within a few hours,100%,100%,f,https://a0.muscache.com/im/users/1589633/profi...,https://a0.muscache.com/im/users/1589633/profi...,NaN,7.0,8.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Basque Country, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.316630,-1.986160,Entire rental unit,Entire home/apt,8,2.0,2 baths,3.0,5.0,"[""Pack \u2019n play/Travel crib"", ""Refrigerato...",$256.00,31,280,31.0,31.0,280.0,280.0,31.0,280.0,NaN,t,29,31,59,59,2025-09-30,14,0,0,59,4,0,0.0,2012-10-02,2024-09-29,4.79,4.77,4.85,4.85,4.92,4.92,4.62,ESFCNT0000200080000301990000000000000000000000...,f,6,5,1,0,0.09
3,309813,https://www.airbnb.com/rooms/309813,20250929230956,2025-09-30,city scrape,Near the beach with terrace Wifi,Meninas is a bright and spacious apartament lo...,The apartment is located in the area known as ...,https://a0.muscache.com/pictures/prohost-api/H...,1589633,https://www.airbnb.com/users/show/1589633,Emy,2012-01-10,"San Sebastian, Spain",My name is Emy and I am the owner of these apa...,within a few hours,100%,100%,f,https://a0.muscache.com/im/users/1589633/profi...,https://a0.muscache.com/im/users/1589633/profi...,NaN,7.0,8.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Basque Country, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.316810,-1.986110,Entire rental unit,Entire home/apt,8,2.0,2 baths,3.0,5.0,"[""Refrigerator"", ""Microwave"", ""Essentials"", ""W...",$256.00,31,124,31.0,31.0,124.0,124.0,31.0,124.0,NaN,t,29,31,31,31,2025-09-30,17,0,0,31,4,0,0.0,2012-03-15,2024-08-24,4.69,4.71,4.82,4.75,4.71,4.81,4.75,ESFCNT0000200080000302050000000000000000000000...,f,6,5,1,0,0.10
4,309828,https://www.airbnb.com/rooms/309828,20250929230956,2025-09-30,city scrape,Impresionante vivienda céntrica con vistas al mar,Belle View is an elegant apartament located on...,The apartment is located in the area known as ...,https://a0.muscache.com/pictures/47130848/bded...,1589633,https://www.airbnb.com/users/show/1589633,Emy,2012-01-10,"San Sebastian, Spain",My name is Emy and I am the owner of these apa...,within a few hours,100%,100%,f,https://a0.muscache.com/im/users/1589633/profi...,https://a0.muscache.com/im/users/1589633/profi...,NaN,7.0,8.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Basque Country, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.314710,-1.985880,Entire rental unit,Entire home/apt,8,2.0,2 baths,3.0,3.0,"[""Refrigerator"", ""Microwave"", ""Essentials"", ""W...",$256.00,31,365,31.0,31.0,365.0,365.0,31.0,365.0,NaN,t,29,31,31,31,2025-09-30,36,2,0,31,2,124,31744.0,2014-01-04,2025-08-01,4.97,4.97,4.91,4.94,4.94,4.97,4.83,ESFCNT0000200080003331600000000000000000000000...,f,6,5,1,0,0.25

In [5]:
df_airbnb.info()

<class 'pandas.DataFrame'>
RangeIndex: 6334 entries, 0 to 6333
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            6334 non-null   int64
 1   listing_url                                   6334 non-null   str
 2   scrape_id                                     6334 non-null   int64
 3   last_scraped                                  6334 non-null   str
 4   source                                        6334 non-null   str
 5   name                                          6334 non-null   str
 6   description                                   6102 non-null   str
 7   neighborhood_overview                         2941 non-null   str
 8   picture_url                                   6334 non-null   str
 9   host_id                                       6334 non-null   int64
 10  host_url                                      6334 non-null   str
 11  host_name                                     6330 non-null   str
 12  host_since                                    6330 non-null   str
 13  host_location                                 4511 non-null   str
 14  host_about                                    2975 non-null   str
 15  host_response_time                            5655 non-null   str
 16  host_response_rate                            5655 non-null   str
 17  host_acceptance_rate                          5962 non-null   str
 18  host_is_superhost                             6155 non-null   str
 19  host_thumbnail_url                            6330 non-null   str
 20  host_picture_url                              6330 non-null   str
 21  host_neighbourhood                            324 non-null    str
 22  host_listings_count                           6330 non-null   float64
 23  host_total_listings_count                     6330 non-null   float64
 24  host_verifications                            6330 non-null   str
 25  host_has_profile_pic                          6330 non-null   str
 26  host_identity_verified                        6330 non-null   str
 27  neighbourhood                                 2941 non-null   str
 28  neighbourhood_cleansed                        6334 non-null   str
 29  neighbourhood_group_cleansed                  6334 non-null   str
 30  latitude                                      6334 non-null   float64
 31  longitude                                     6334 non-null   float64
 32  property_type                                 6334 non-null   str
 33  room_type                                     6334 non-null   str
 34  accommodates                                  6334 non-null   int64
 35  bathrooms                                     5652 non-null   float64
 36  bathrooms_text                                6322 non-null   str
 37  bedrooms                                      6171 non-null   float64
 38  beds                                          5645 non-null   float64
 39  amenities                                     6334 non-null   str
 40  price                                         5651 non-null   str
 41  minimum_nights                                6334 non-null   int64
 42  maximum_nights                                6334 non-null   int64
 43  minimum_minimum_nights                        6329 non-null   float64
 44  maximum_minimum_nights                        6329 non-null   float64
 45  minimum_maximum_nights                        6329 non-null   float64
 46  maximum_maximum_nights                        6329 non-null   float64
 47  minimum_nights_avg_ntm                        6334 non-null   float64
 48  maximum_nights_avg_ntm                        6334 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              6188 non-null   str
 51  availability_30                               6334 non-null   int64
 52  availability_60                               6334 non-null   int64
 53  availability_90                               6334 non-null   int64
 54  availability_365                              6334 non-null   int64
 55  calendar_last_scraped                         6334 non-null   str
 56  number_of_reviews                             6334 non-null   int64
 57  number_of_reviews_ltm                         6334 non-null   int64
 58  number_of_reviews_l30d                        6334 non-null   int64
 59  availability_eoy                              6334 non-null   int64
 60  number_of_reviews_ly                          6334 non-null   int64
 61  estimated_occupancy_l365d                     6334 non-null   int64
 62  estimated_revenue_l365d                       5651 non-null   float64
 63  first_review                                  5734 non-null   str
 64  last_review                                   5734 non-null   str
 65  review_scores_rating                          5734 non-null   float64
 66  review_scores_accuracy                        5734 non-null   float64
 67  review_scores_cleanliness                     5734 non-null   float64
 68  review_scores_checkin                         5734 non-null   float64
 69  review_scores_communication                   5734 non-null   float64
 70  review_scores_location                        5734 non-null   float64
 71  review_scores_value                           5734 non-null   float64
 72  license                                       5031 non-null   str
 73  instant_bookable                              6334 non-null   str
 74  calculated_host_listings_count                6334 non-null   int64
 75  calculated_host_listings_count_entire_homes   6334 non-null   int64
 76  calculated_host_listings_count_private_rooms  6334 non-null   int64
 77  calculated_host_listings_count_shared_rooms   6334 non-null   int64
 78  reviews_per_month                             5734 non-null   float64
dtypes: float64(23), int64(20), str(36)
memory usage: 3.8 MB

In [ ]:
# Turn the string "price" data into numeric
df_airbnb["price"] = (
    df_airbnb["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [ ]:
# Check for NaN's in the "price" column
df_airbnb["price"].isna().sum()

np.int64(683)

In [ ]:
# Drop all the rows whose price value is NaN, imputation is not an option since they're the target values
df_airbnb = df_airbnb.dropna(subset=["price"]).copy()

In [ ]:
# Create helper bins (quantiles) for stratified train/test split on price
df_airbnb["price_bin"] = pd.qcut(df_airbnb["price"], q=5, duplicates="drop")

In [ ]:
# Create input and output variables
X = df_airbnb.drop(columns=["price"])
y = df_airbnb["price"]

In [ ]:
# Split data into 80% trainig and 20% test sets using stratification on price bins.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=X["price_bin"]
)

In [ ]:
# Remove the price bins from each set. 
X_train = X_train.drop(columns=["price_bin"])
X_test = X_test.drop(columns=["price_bin"])

In [16]:
X_train.shape

(4520, 78)

In [17]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 4520 entries, 1592 to 1552
Data columns (total 78 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            4520 non-null   int64
 1   listing_url                                   4520 non-null   str
 2   scrape_id                                     4520 non-null   int64
 3   last_scraped                                  4520 non-null   str
 4   source                                        4520 non-null   str
 5   name                                          4520 non-null   str
 6   description                                   4354 non-null   str
 7   neighborhood_overview                         2108 non-null   str
 8   picture_url                                   4520 non-null   str
 9   host_id                                       4520 non-null   int64
 10  host_url                                      4520 non-null   str
 11  host_name                                     4518 non-null   str
 12  host_since                                    4518 non-null   str
 13  host_location                                 3241 non-null   str
 14  host_about                                    2136 non-null   str
 15  host_response_time                            4170 non-null   str
 16  host_response_rate                            4170 non-null   str
 17  host_acceptance_rate                          4302 non-null   str
 18  host_is_superhost                             4389 non-null   str
 19  host_thumbnail_url                            4518 non-null   str
 20  host_picture_url                              4518 non-null   str
 21  host_neighbourhood                            228 non-null    str
 22  host_listings_count                           4518 non-null   float64
 23  host_total_listings_count                     4518 non-null   float64
 24  host_verifications                            4518 non-null   str
 25  host_has_profile_pic                          4518 non-null   str
 26  host_identity_verified                        4518 non-null   str
 27  neighbourhood                                 2108 non-null   str
 28  neighbourhood_cleansed                        4520 non-null   str
 29  neighbourhood_group_cleansed                  4520 non-null   str
 30  latitude                                      4520 non-null   float64
 31  longitude                                     4520 non-null   float64
 32  property_type                                 4520 non-null   str
 33  room_type                                     4520 non-null   str
 34  accommodates                                  4520 non-null   int64
 35  bathrooms                                     4516 non-null   float64
 36  bathrooms_text                                4515 non-null   str
 37  bedrooms                                      4518 non-null   float64
 38  beds                                          4509 non-null   float64
 39  amenities                                     4520 non-null   str
 40  minimum_nights                                4520 non-null   int64
 41  maximum_nights                                4520 non-null   int64
 42  minimum_minimum_nights                        4518 non-null   float64
 43  maximum_minimum_nights                        4518 non-null   float64
 44  minimum_maximum_nights                        4518 non-null   float64
 45  maximum_maximum_nights                        4518 non-null   float64
 46  minimum_nights_avg_ntm                        4520 non-null   float64
 47  maximum_nights_avg_ntm                        4520 non-null   float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              4494 non-null   str
 50  availability_30                               4520 non-null   int64
 51  availability_60                               4520 non-null   int64
 52  availability_90                               4520 non-null   int64
 53  availability_365                              4520 non-null   int64
 54  calendar_last_scraped                         4520 non-null   str
 55  number_of_reviews                             4520 non-null   int64
 56  number_of_reviews_ltm                         4520 non-null   int64
 57  number_of_reviews_l30d                        4520 non-null   int64
 58  availability_eoy                              4520 non-null   int64
 59  number_of_reviews_ly                          4520 non-null   int64
 60  estimated_occupancy_l365d                     4520 non-null   int64
 61  estimated_revenue_l365d                       4520 non-null   float64
 62  first_review                                  4098 non-null   str
 63  last_review                                   4098 non-null   str
 64  review_scores_rating                          4098 non-null   float64
 65  review_scores_accuracy                        4098 non-null   float64
 66  review_scores_cleanliness                     4098 non-null   float64
 67  review_scores_checkin                         4098 non-null   float64
 68  review_scores_communication                   4098 non-null   float64
 69  review_scores_location                        4098 non-null   float64
 70  review_scores_value                           4098 non-null   float64
 71  license                                       3682 non-null   str
 72  instant_bookable                              4520 non-null   str
 73  calculated_host_listings_count                4520 non-null   int64
 74  calculated_host_listings_count_entire_homes   4520 non-null   int64
 75  calculated_host_listings_count_private_rooms  4520 non-null   int64
 76  calculated_host_listings_count_shared_rooms   4520 non-null   int64
 77  reviews_per_month                             4098 non-null   float64
dtypes: float64(23), int64(20), str(35)
memory usage: 2.7 MB

In [15]:
X_train.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
1592,35556537,https://www.airbnb.com/rooms/35556537,20250929230956,2025-09-30,city scrape,"NUEVO APARTAMENTO, junto CASCO VIEJO",Enjoy a few days in Bilbao in this modern and ...,"Next to Casco Viejo, a fashionable neighborhoo...",https://a0.muscache.com/pictures/30549523-bde0...,267100434,https://www.airbnb.com/users/show/267100434,Lys,2019-06-08,"Bilbao, Spain","Hola, yo seré vuestra anfitriona. \nPara cualq...",within an hour,100%,100%,t,https://a0.muscache.com/im/pictures/user/938b4...,https://a0.muscache.com/im/pictures/user/938b4...,NaN,1.0,1.0,"['email', 'phone']",t,t,"Bilbao, Vizkaia, Spain, Spain",Bilbao,Vizcaya,43.256507,-2.928715,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,3.0,"[""Pack \u2019n play/Travel crib"", ""Refrigerato...",1,1125,1.0,3.0,1125.0,1125.0,1.3,1125.0,NaN,t,7,29,59,149,2025-09-30,359,71,5,62,73,255,31365.0,2019-06-15,2025-09-24,4.91,4.95,4.98,4.97,4.99,4.60,4.80,ESFCTU00004802700084705300000000000000000000EB...,f,1,1,0,0,4.68
1382,31667896,https://www.airbnb.com/rooms/31667896,20250929230956,2025-09-30,city scrape,Apartamento nuevo en el centro de San Sebastián,Apartment in the center of San Sebastian for ...,"Located in the old part, in the heart of San S...",https://a0.muscache.com/pictures/3176ad0f-4ba1...,133395812,https://www.airbnb.com/users/show/133395812,Jaione,2017-06-04,"San Sebastián, Spain","Emprendedora, sociable, creativa e inquieta. M...",within a few hours,90%,96%,f,https://a0.muscache.com/im/pictures/user/4a4e0...,https://a0.muscache.com/im/pictures/user/4a4e0...,NaN,10.0,10.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Euskadi, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.324610,-1.984080,Entire rental unit,Entire home/apt,4,1.0,1 bath,3.0,4.0,"[""Refrigerator"", ""Microwave"", ""Hot water kettl...",30,300,30.0,30.0,300.0,300.0,30.0,300.0,NaN,t,25,50,76,287,2025-09-30,5,2,0,79,1,120,13800.0,2019-06-30,2025-07-31,5.00,5.00,5.00,5.00,5.00,4.80,4.60,ESFCNT0000200080002542430000000000000000000000...,f,10,10,0,0,0.07
2536,50127094,https://www.airbnb.com/rooms/50127094,20250929230956,2025-09-30,city scrape,Boulevard Suite: 2 min from La Concha Beach,UNBEATABLE LOCATION! This flat is the perfect ...,"Right in the Boulevard de San Sebastian, the h...",https://a0.muscache.com/pictures/miso/Hosting-...,2470030,https://www.airbnb.com/users/show/2470030,Javier,2012-05-26,"San Sebastián, Spain","BIENVENIDO, ONGI ETORRI, WELLCOME! \n\nWe are ...",within an hour,100%,97%,t,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,NaN,27.0,33.0,"['email', 'phone']",t,t,"Donostia-San Sebastian, Euskadi, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.323890,-1.982550,Entire rental unit,Entire home/apt,6,2.0,2 baths,3.0,5.0,"[""Pack \u2019n play/Travel crib"", ""Refrigerato...",1,1125,1.0,4.0,1125.0,1125.0,3.0,1125.0,NaN,t,10,28,51,259,2025-09-30,37,10,3,54,4,60,25320.0,2021-07-31,2025-09-28,4.95,4.95,4.86,4.97,4.97,4.97,4.84,ESFCTU00002000800051403300000000000000000000ES...,t,25,25,0,0,0.73
986,23840102,https://www.airbnb.com/rooms/23840102,20250929230956,2025-09-30,city scrape,Pasea a la playa de la Concha desde este nuevo...,Designed by Slow & Chic in a modern and cozy s...,"In downtown San Sebastian, just minutes from L...",https://a0.muscache.com/pictures/a07051ff-2a40...,179009019,https://www.airbnb.com/users/show/179009019,Chic Donosti,2018-03-17,"Donostia-San Sebastian, Spain",Español e Inglés tanto hablado como escrito.,within an hour,97%,100%,t,https://a0.muscache.com/im/pictures/user/513bc...,https://a0.muscache.com/im/pictures/user/513bc...,NaN,3.0,3.0,"['email', 'phone', 'work_email']",t,t,"Donostia-San Sebastian, Euskadi, Spain",Donostia-San SebastiÃ¡n,GuipÃºzcoa,43.314530,-1.981370,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,2.0,"[""Pack \u2019n play/Travel crib"", ""Children\u2...",2,30,1.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,1,17,38,287,2025-09-30,513,81,9,39,69,255,32895.0,2018-03-25,2025-09-27,4.91,4.86,4.95,4.94,4.98,4.94,4.80,ESFCTU00002000800023810600000000000000000000ES...,t,3,3,0,0,5.60
4449,1049174016373077248,https://www.airbnb.com/rooms/1049174016373077248,20250929230956,2025-09-30,city scrape,Vitoria Palacio Álava-V. | Family Studio + Bal...,"At limehome, we believe that everyone deserves...",Our limehome is located in the impressive Pala...,https://a0.muscache.com/pictures/miso/Hosting-...,418270816,https://www.airbnb.com/users/show/418270816,Limehome,2021-08-13,NaN,"At Limehome, we believe that everyone deserves...",within an hour,99%,99%,f,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Nové Město,967.0,1058.0,"['email', 'phone']",t,t,"Gasteiz, Euskadi, Spain",Vitoria-Gasteiz,Ãlava,42.851525,-2.673562,Entire rental unit,Entire home/apt,6,1.0,1 bath,1.0,3.0,"[""Refrigerator"", ""Microwave"", ""Shower gel"", ""E...",1,365,1.0,1.0,999.0,999.0,1.0,999.0,NaN,t,9,24,37,228,2025-09-30,8,3,0,37,7,18,5256.0,2024-02-28,2025-01-06,4.75,4.63,4.63,4.63,4.38,4.88,4.63,Exempt,t,18,18,0,0,0.41